"""
This odmlib v0.2.0 snippet was created and used to demonstrate new features to convert Define-XML v2.1 metadata
into Dataset-JSON v1.1 datasets for easy processing by applications that prefer tabular data structures.

This snippet differs from define2dsj.py because it flattens a Define-XML template generated by the 360i
Data Definition Engine. This template contains __PLACEHOLDER__ for values where the content was not available
when generating metadata using USDM + BCs + DSSs. The purpose of this snippet is the flatten that template and to
generate a metadata spreadsheet so a user could replace those placeholders with actual values. In 360i, we plan
to replace those values using an automated process, and this snippet provides an alternative approach.
"""
import json
import xlsxwriter as XLS
import odmlib.define_loader as DL
import odmlib.loader as LD
from odmlib.dataset_json_1_1.define_flattener import DefineFlattener
from odmlib.dataset_json_1_1.define_builder import DefineBuilder
from odmlib import (
    permissive,
    OdmlibError,
    OdmlibTypeError,
    OdmlibValidationError,
)

# load a Define-XML v2.1 file to convert to Dataset-JSON v1.1
loader = LD.ODMLoader(DL.XMLDefineLoader(
    model_package='define_2_1',
    ns_uri='http://www.cdisc.org/ns/def/v2.1',
))

# must use permissive to load this Define-XML as the __PLACEHOLDER__ values violate the model constraints
with permissive():
    loader.open_odm_document('data/define-360i.xml')
    odm = loader.root()

# flatten the template define.xml metadata
flattener = DefineFlattener(odm)
datasets = flattener.flatten_all()

# inspect each of the metadata datasets
print(f"Datasets created by flattening the Define-XML template:")
for name, ds in datasets.items():
    print(f"{name}: {ds.records} rows, {len(ds.columns)} columns")

# write out the datasets to files
print(f"\nDatasets path and filenames when writing the metadata datasets:")
paths = flattener.write_all("data/")
for p in paths:
    print(p)

# print the column names and values from the study dataset
study = datasets["study"]
print(f"\nstudy dataset column names: \n{study.column_names}")
print(study.rows[0])
print()

# print the variable OID, name, and data type and for each variable in the DM domain
variables = datasets["variables"]
col_names = variables.column_names
dm_vars = [r for r in variables.rows
           if r[col_names.index("DatasetOID")] == "IG.DM"]
for v in dm_vars:
    print(f"  {v[col_names.index('ItemOID')]}: {v[col_names.index('Name')]} ({v[col_names.index('DataType')]})")


# print the datasets dataset
print("\nFor the datasets dataset, print the entire dictionary as JSON:")
ds = datasets["datasets"]
print(json.dumps(ds.to_dict(), indent=2))

# next generate a metadata spreadsheet from the metadata Dataset-JSON datasets
xlsx_file = "data/define-360i.xlsx"
workbook = XLS.Workbook(xlsx_file, {"strings_to_numbers": False})
header_format = workbook.add_format({"bold": True, "bg_color": "#CCFFFF", "border": True, "border_color": "black"})
for name, ds in datasets.items():
    ws_name = name.replace("_", " ").title()
    worksheet = workbook.add_worksheet(ws_name)
    for col_idx, col_name in enumerate(ds.column_names):
        worksheet.write(1, col_idx, col_name, header_format)
        worksheet.set_column(1, col_idx, 30)
    # some datasets may be empty
    if not ds.rows:
        continue
    for r, row in enumerate(ds.rows, 0):
        for c, col in enumerate(row, 0):
            try:
                worksheet.write(r+2, c, col)
            except UnicodeDecodeError as ue:
                print(f"Encoding error writing load file for row {row} and col {col}: {ue}")
workbook.close()

# print some metrics from the original define-xml file
print(f"\nOriginal ODM:")
print(f"  FileOID: {odm.FileOID}")
print(f"  Study OID: {odm.Study.OID}")
mdv = odm.Study.MetaDataVersion
print(f"  ItemGroupDefs: {len(mdv.ItemGroupDef)}")
print(f"  ItemDefs: {len(mdv.ItemDef)}")
print(f"  CodeLists: {len(mdv.CodeList)}")
print(f"  MethodDefs: {len(mdv.MethodDef)}")


# rebuild the Define-XML from the flattened datasets and print some metrics from the round-trip define-xml
with permissive():
    rebuilt = DefineBuilder(datasets).build()
print(f"\nRebuilt ODM:")
print(f"  FileOID: {rebuilt.FileOID}")
print(f"  Study OID: {rebuilt.Study.OID}")
mdv = rebuilt.Study.MetaDataVersion
print(f"  ItemGroupDefs: {len(mdv.ItemGroupDef)}")
print(f"  ItemDefs: {len(mdv.ItemDef)}")
print(f"  CodeLists: {len(mdv.CodeList)}")
print(f"  MethodDefs: {len(mdv.MethodDef)}")

# now write the newly rebuilt Define-XML to a file
with permissive():
    rebuilt.write_xml("data/rebuilt-define-360i.xml")
print("Define-XML written to rebuilt-define-360i.xml")